version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/react
    overwrite: yes
file_exists_behavior: OVERWRITE
permissions:
  - object: /home/ubuntu/react
    owner: ubuntu
    group: ubuntu
    mode: 755
hooks:
  AfterInstall:
    - location: deploy.sh
      timeout: 100
      runas: ubuntu
